# Site settings

# NB! Set your site's url, otherwise nothing will work
url: "https://dev-the-desai.github.io/"

# Google tracking id
google-tracking-id: "UA-XXXXXXXX-X"

#############
# HTML Head #
#############

lang: "en"
author: "Sean 'P. Diddy' Combs"
title: "Diddy Party"
description: "Yo, it’s Diddy—spinnin’ the wildest takes on my own chaos. Lawsuits, jail pasta, and bling—none of this is serious, but it’s all fire. Laugh at my mess."
keywords: "p diddy, sean combs, satire, parody, lawsuits, jail, humor"
favicon: "/img/diddy_favicon.ico"

################
# Header layout#
################
black-favicon: "/img/diddy_black.ico"
background-img: "/img/mallu_bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

quote: "Can’t stop, won’t stop—unless the feds say so!"
me-img: "/img/mallu_bg.jpg"

#######
# Blog #
########

post-preview-words: 96
paginate: 5
email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "diddy-satire-comments"

############
# Timeline #
############

events:
  - image: "/img/timeline/m2.jpg"
    date: "1990 - 2024"
    description: "Threw parties so wild they called ‘em crimes!"
  - image: "/img/timeline/m3.jpg"
    date: "September 2024 - Today"
    description: "Chillin’ in Brooklyn jail, droppin’ bars instead of beats"

# First image of the Timeline
timeline-img: "/img/timeline/m1.jpg"

###########
# Contact #
###########

email: "diddy.lockedup@gmail.com"
# Set a url pointing to your publish PGP Public Key here, and it will appear in the Contact section
pgp: False

################
# Author Blurb #
################

author_blurb:
  "I’m P. Diddy, ya boy from the block turned jailhouse rock. Once ran Bad Boy, now runnin’ from the law—catch me mockin’ my own downfall with a side of bling."
author_blurb_image: "/img/diddy_mugshot_author.png"

##################
# Social Buttons #
##################

social:
  - icon: "github"
    url: "https://github.com/dev-the-desai"
  - icon: "linkedin-in"
    url: "https://www.linkedin.com"
  - icon: "x-twitter"
    url: "https://twitter.com/DiddySatireX"
  - icon: "rss"
    url: "https://dev-the-desai.github.io/feed.xml"

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  About: "about"
  Blog: "latest-post"
  Timeline: "timeline"
  Contact: "contact"

# Exclusion list from the generated _site
exclude:
  - LICENSE
  - README.md
  - CONTRIBUTING
  - CONTRIBUTORS
  - scripts
  - Dockerfile
  - docker-compose.yml

# Pagination path
paginate_path: "blog/page:num/"

# Enable minification SASS
sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-spaceship